FROM grafana/alloy:latest
# Для Debian/Ubuntu:
# RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y curl iputils-ping && rm -rf /var/lib/apt/lists/*
